"use client";

import { useMemo, useRef, useState } from "react";
type Mode="tree"|"linear"|"sort";type Node={id:number;value:string;x:number;y:number;color:"green"|"red"|"black"};type Edge={a:number;b:number};type TextItem={id:number;text:string;x:number;y:number};
const start:Node[]=[{id:1,value:"30",x:350,y:55,color:"black"},{id:2,value:"20",x:220,y:165,color:"red"},{id:3,value:"40",x:480,y:165,color:"black"},{id:4,value:"10",x:135,y:275,color:"green"}];
function sortFrames(values:number[],kind:string){const a=[...values],frames=[{a:[...a],msg:"開始"}];if(kind==="bubble")for(let i=0;i<a.length;i++)for(let j=0;j<a.length-i-1;j++){frames.push({a:[...a],msg:`${a[j]} と ${a[j+1]} を比較`});if(a[j]>a[j+1]){[a[j],a[j+1]]=[a[j+1],a[j]];frames.push({a:[...a],msg:"交換"});}}else if(kind==="selection")for(let i=0;i<a.length;i++){let m=i;for(let j=i+1;j<a.length;j++)if(a[j]<a[m])m=j;[a[i],a[m]]=[a[m],a[i]];frames.push({a:[...a],msg:`最小値を位置 ${i} へ`});}else for(let i=1;i<a.length;i++){const x=a[i];let j=i-1;while(j>=0&&a[j]>x){a[j+1]=a[j];j--;}a[j+1]=x;frames.push({a:[...a],msg:`${x} を整列済み部分へ挿入`});}return frames;}
export default function StructureLab({onAddNote}:{onAddNote:(t:string)=>void}){const[mode,setMode]=useState<Mode>("tree"),[nodes,setNodes]=useState(start),[edges,setEdges]=useState<Edge[]>([{a:1,b:2},{a:1,b:3},{a:2,b:4}]),[selected,setSelected]=useState<number|null>(null),[connectFrom,setConnectFrom]=useState<number|null>(null),[texts,setTexts]=useState<TextItem[]>([{id:1,text:"自由に動かして木を作る",x:18,y:18}]);const canvas=useRef<HTMLDivElement>(null),drag=useRef<{id:number;dx:number;dy:number}|null>(null);const[linearKind,setLinearKind]=useState("stack"),[values,setValues]=useState([8,3,10,1,6]),[value,setValue]=useState(12),[sortKind,setSortKind]=useState("bubble"),[frame,setFrame]=useState(0);
  const frames=useMemo(()=>sortFrames(values,sortKind),[values,sortKind]);
  function addNode(){const id=Date.now();setNodes(v=>[...v,{id,value:String(value),x:300+(v.length%4)*65,y:180+(v.length%2)*90,color:"green"}]);setSelected(id);}
  function clickNode(id:number){if(connectFrom&&connectFrom!==id){setEdges(v=>[...v,{a:connectFrom,b:id}]);setConnectFrom(null);}else setSelected(id);}
  function pointerDown(e:React.PointerEvent,n:Node){e.stopPropagation();clickNode(n.id);const r=canvas.current!.getBoundingClientRect();drag.current={id:n.id,dx:e.clientX-r.left-n.x,dy:e.clientY-r.top-n.y};}
  function move(e:React.PointerEvent){if(!drag.current||!canvas.current)return;const r=canvas.current.getBoundingClientRect(),d=drag.current;setNodes(v=>v.map(n=>n.id===d.id?{...n,x:Math.max(8,Math.min(r.width-55,e.clientX-r.left-d.dx)),y:Math.max(8,Math.min(r.height-55,e.clientY-r.top-d.dy))}:n));}
  function addText(){const text=window.prompt("置くテキスト")?.trim();if(text)setTexts(v=>[...v,{id:Date.now(),text,x:30+v.length*24,y:60+v.length*28}]);}
  const suggestion=useMemo(()=>{if(nodes.length<3)return"ノードを追加し、親子を矢印で接続してください";const root=[...nodes].sort((a,b)=>a.y-b.y)[0];const left=nodes.filter(n=>n.x<root.x&&n.y>root.y).length,right=nodes.filter(n=>n.x>root.x&&n.y>root.y).length,bf=left-right;if(bf>=2)return`${root.value} の左側が重い（簡易BF +${bf}）。次は右回転を試そう`;if(bf<=-2)return`${root.value} の右側が重い（簡易BF ${bf}）。次は左回転を試そう`;return`現在の木は簡易判定で平衡です（根のBF ${bf}）`;},[nodes,edges]);
  function applyRotation(){const root=[...nodes].sort((a,b)=>a.y-b.y)[0];const left=nodes.filter(n=>n.x<root.x&&n.y>root.y),right=nodes.filter(n=>n.x>root.x&&n.y>root.y);const child=left.length>right.length?left.sort((a,b)=>a.y-b.y)[0]:right.sort((a,b)=>a.y-b.y)[0];if(!child)return;setNodes(v=>v.map(n=>n.id===child.id?{...n,x:350,y:55}:n.id===root.id?{...n,x:left.length>right.length?470:230,y:165}:n));}
  return <section className="lab-page structure-lab"><div className="feature-hero"><span className="structure-icon">⌘</span><div><p className="eyebrow">FREE STRUCTURE STUDIO</p><h1>Data Structure Lab</h1><p>自由に作って動かし、いまの状態から次の操作を学べます。</p></div></div><div className="structure-tabs"><button className={mode==="tree"?"active":""} onClick={()=>setMode("tree")}>Tree・回転</button><button className={mode==="linear"?"active":""} onClick={()=>setMode("linear")}>Stack・List・Array</button><button className={mode==="sort"?"active":""} onClick={()=>setMode("sort")}>Sort Flip</button></div>
  {mode==="tree"&&<><div className="studio-tools panel"><input type="number" value={value} onChange={e=>setValue(Number(e.target.value))}/><button onClick={addNode}>○ ノード</button><button onClick={()=>{if(selected)setConnectFrom(selected)}}>↗ 矢印</button><button onClick={addText}>T テキスト</button><button onClick={()=>selected&&setNodes(v=>v.map(n=>n.id===selected?{...n,color:n.color==="green"?"red":n.color==="red"?"black":"green"}:n))}>● 色変更</button><button className="danger" onClick={()=>{if(selected){setNodes(v=>v.filter(n=>n.id!==selected));setEdges(v=>v.filter(e=>e.a!==selected&&e.b!==selected));setSelected(null);}}}>削除</button></div><div className="free-canvas panel" ref={canvas} onPointerMove={move} onPointerUp={()=>drag.current=null}>{edges.map((e,i)=>{const a=nodes.find(n=>n.id===e.a),b=nodes.find(n=>n.id===e.b);if(!a||!b)return null;return <i key={i} className="free-edge" style={{left:a.x+26,top:a.y+26,width:Math.hypot(b.x-a.x,b.y-a.y),transform:`rotate(${Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI}deg)`}}/>})}{texts.map(t=><span key={t.id} className="free-text" style={{left:t.x,top:t.y}} onDoubleClick={()=>setTexts(v=>v.filter(x=>x.id!==t.id))}>{t.text}</span>)}{nodes.map(n=><button key={n.id} className={`free-node ${n.color} ${selected===n.id?"selected":""} ${connectFrom===n.id?"connecting":""}`} style={{left:n.x,top:n.y}} onPointerDown={e=>pointerDown(e,n)} onDoubleClick={()=>{const x=window.prompt("値を編集",n.value);if(x)setNodes(v=>v.map(q=>q.id===n.id?{...q,value:x}:q));}}>{n.value}</button>)}</div><div className="next-action panel"><div><p className="eyebrow">NEXT ROTATION</p><b>{suggestion}</b></div><button onClick={applyRotation}>提案された回転を実行</button><button onClick={()=>onAddNote(`現在の木：${nodes.map(n=>n.value).join(", ")}\n${suggestion}`)}>ノートへ</button></div></>}
  {mode==="linear"&&<><div className="studio-tools panel"><select value={linearKind} onChange={e=>setLinearKind(e.target.value)}><option value="stack">Stack</option><option value="linked">Linked List</option><option value="array">Array</option></select><input type="number" value={value} onChange={e=>setValue(Number(e.target.value))}/><button onClick={()=>setValues(v=>[...v,value])}>＋ 数字ブロック</button><button onClick={()=>setValues(v=>v.slice(0,-1))}>− 末尾削除</button><button onClick={addText}>T テキスト</button></div><div className={`linear-canvas panel ${linearKind}`}><span className="structure-label">{linearKind.toUpperCase()}</span><div className="value-chain">{values.map((v,i)=><button key={`${v}-${i}`} onDoubleClick={()=>setValues(x=>x.filter((_,j)=>j!==i))}>{v}{linearKind==="linked"&&<i>→</i>}</button>)}</div>{texts.map(t=><span key={t.id} className="linear-text" onDoubleClick={()=>setTexts(v=>v.filter(x=>x.id!==t.id))}>{t.text}</span>)}</div><div className="complexity-row"><b>現在の時間計算量</b><span>参照 {linearKind==="array"?"O(1)":"O(n)"}</span><span>末尾追加 {linearKind==="linked"?"O(1)*":"O(1)"}</span><span>検索 O(n)</span><small>* tailポインタがある場合</small></div></>}
  {mode==="sort"&&<><div className="studio-tools panel"><select value={sortKind} onChange={e=>{setSortKind(e.target.value);setFrame(0)}}><option value="bubble">Bubble Sort</option><option value="selection">Selection Sort</option><option value="insertion">Insertion Sort</option></select><input value={values.join(",")} onChange={e=>setValues(e.target.value.split(",").map(Number).filter(Number.isFinite))}/><button onClick={addText}>T テキスト</button></div><div className="sort-flip panel"><div className="flip-head"><button onClick={()=>setFrame(f=>Math.max(0,f-1))}>←</button><div><b>FRAME {frame+1} / {frames.length}</b><span>{frames[frame]?.msg}</span></div><button onClick={()=>setFrame(f=>Math.min(frames.length-1,f+1))}>→</button></div><div className="sort-blocks">{frames[frame]?.a.map((v,i)=><span key={i} style={{height:45+v*5}}><b>{v}</b></span>)}</div>{texts.map(t=><span key={t.id} className="sort-text" onDoubleClick={()=>setTexts(v=>v.filter(x=>x.id!==t.id))}>{t.text}</span>)}</div><div className="complexity-row"><b>{sortKind} の計算量</b><span>Best {sortKind==="bubble"?"O(n)":"O(n²)"}</span><span>Average O(n²)</span><span>Worst O(n²)</span></div></>}
  </section>}
